apiVersion: v1
kind: Service
metadata:
  name: nodehelloworld
spec:
  type: ClusterIP
  selector:
    app: nodehelloworld
  ports:
    - name: webserver
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: grpcserver
      protocol: TCP
      port: 8081
      targetPort: 8081