apiVersion: v1
kind: Service
metadata:
  name: gohelloworld-nodeport
spec:
  type: NodePort
  selector:
    app: gohelloworld
  ports:
    - name: webserver
      protocol: TCP
      port: 3000
      targetPort: 3000
