apiVersion: v1
kind: Service
metadata:
  name: gohelloworld
spec:
  type: ClusterIP
  selector:
    app: gohelloworld
  ports:
    - name: webserver
      protocol: TCP
      port: 3000
      targetPort: 3000
    - name: grpcserver
      protocol: TCP
      port: 3001
      targetPort: 3001