apiVersion: v1
kind: Service
metadata:
  name: nodehelloworld-nodeport
spec:
  type: NodePort
  selector:
    app: nodehelloworld
  ports:
    - name: webserver
      protocol: TCP
      port: 8080
      targetPort: 8080